import type { Metadata } from 'next';
// import { Inter } from "next/font/google";
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import StyledComponentsRegistry from '../../lib/registry';

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// export const

const RootLayout = ({ children }: React.PropsWithChildren) => (
    <html lang="en">
        <body>
            <AntdRegistry>
                <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            </AntdRegistry>
        </body>
    </html>
);

export default RootLayout;
