import type { Metadata } from 'next';
// import { Inter } from "next/font/google";
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { StoreProvider } from '@/redux/store/StoreProvider';
import { Toaster } from 'react-hot-toast';

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: 'MYS Tinasoft',
    description: 'Generated by create next app',
};

// export const

const RootLayout = ({ children }: React.PropsWithChildren) => (
    <StoreProvider>
        <html lang="en">
            <body>
                <Toaster />
                <AntdRegistry>{children}</AntdRegistry>
            </body>
        </html>
    </StoreProvider>
);

export default RootLayout;
